jsdoc2md ./src/array.js > ./docs/array.md
jsdoc2md ./src/call.js > ./docs/call.md
jsdoc2md ./src/datetime-helper.js > ./docs/datetime-helper.md
jsdoc2md ./src/debounce.js > ./docs/debounce.md
jsdoc2md ./src/event-emitter.js > ./docs/event-emitter.md
jsdoc2md ./src/filter.js > ./docs/filter.md
jsdoc2md ./src/generation.js > ./docs/generation.md
jsdoc2md ./src/money.js > ./docs/money.md
jsdoc2md ./src/num-to-cn.js > ./docs/num-to-cn.md
jsdoc2md ./src/number.js > ./docs/number.md
jsdoc2md ./src/storage.js > ./docs/storage.md